/**
 * Loads metrics_catalog.json (generated by publicschema-build's
 * `publicschema build-site-data --kinds=metrics_catalog` subcommand) and
 * exposes typed accessors for the metrics index and detail pages.
 *
 * Uses the Vite alias @metrics-data (configured in astro.config.mjs) so the
 * path resolves correctly in both dev and build.
 */

// @ts-ignore - resolved by Vite alias
import metricsData from "@metrics-data";

interface MultilingualText {
  en: string;
  fr?: string;
  es?: string;
}

export interface MetricCatalog {
  /** Filename stem of the catalog file (e.g. ``ilo_sdg``). Stable URL slug. */
  key: string;
  /** Authored ``id:`` field at the top of the catalog file. */
  id: string;
  title: string;
  description: string;
  source: string;
  license: string;
  path: string;
  metric_count: number;
}

export interface MetricCalculationPopulation {
  population_type: string;
  language?: string;
  criteria?: string;
}

export interface MetricCalculationStratifier {
  code?: string;
  language?: string;
  criteria?: string;
  /** Nested compound stratifiers; spec allows one level of components. */
  components?: MetricCalculationStratifier[];
}

export interface MetricCalculation {
  scoring?: string;
  subject_class?: string;
  populations?: MetricCalculationPopulation[];
  stratifiers?: MetricCalculationStratifier[];
  rate_aggregation?: string;
  improvement_notation?: string;
  libraries?: string[];
}

export interface Metric {
  id: string;
  catalog_key: string;
  path: string;
  uri: string;
  label: MultilingualText;
  definition: MultilingualText;
  value_type: string;
  unit: string | null;
  decimals: number | null;
  dimensions: string[];
  attributes: string[];
  aligns_with: string[];
  concept_uri: string | null;
  calculation: MetricCalculation | null;
  core: boolean;
  version: string;
  status: string;
}

export interface MetricsCatalogData {
  meta: {
    schema_version: string;
    catalog_count: number;
    metric_count: number;
  };
  catalogs: Record<string, MetricCatalog>;
  metrics: Record<string, Metric>;
}

export function loadMetricsCatalog(): MetricsCatalogData {
  return metricsData as MetricsCatalogData;
}

/** Metrics grouped by their catalog_key, sorted by metric id within each group. */
export function metricsByCatalog(
  data: MetricsCatalogData,
): Record<string, Metric[]> {
  const grouped: Record<string, Metric[]> = {};
  for (const catalogKey of Object.keys(data.catalogs)) {
    grouped[catalogKey] = [];
  }
  for (const metric of Object.values(data.metrics)) {
    (grouped[metric.catalog_key] ||= []).push(metric);
  }
  for (const list of Object.values(grouped)) {
    list.sort((a, b) => a.id.localeCompare(b.id));
  }
  return grouped;
}

/** Build the static-paths slug list for ``/metrics/[...slug]``. */
export function metricSlugs(data: MetricsCatalogData): string[] {
  return Object.values(data.metrics).map((m) => `${m.catalog_key}/${m.id}`);
}

/** Catalog slug list for ``/metrics/`` (index entry per catalog). */
export function catalogSlugs(data: MetricsCatalogData): string[] {
  return Object.keys(data.catalogs);
}
